name: Test and Deploy CosmosDBTriger

on:
  #push:
    #branches: [ main ]
    #paths-ignore: 
      #- '**/README.md'
      #- '**/*.yml'
  #pull_request:
    #branches: [ main ]
  workflow_dispatch:
  
env:
  AZURE_CosmosDBTrigger_FUNCTIONAPP_NAME: CosmosDBTrigger-FA
  AZURE_FUNCTION_CosmosDBTrigger_PATH: CosmosDBTrigger/CosmosDBTrigger
  CosmosDBTrigger_ROOT_SOLUTION_PATH: 'CosmosDBTrigger'
  DOTNET_VERSION: 3.1.x
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:    
      - name: Get the latest source code commit
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{ env.CosmosDBTrigger_ROOT_SOLUTION_PATH }}

      - name: Build for Testing
        run: dotnet build --no-restore
        working-directory: ${{ env.CosmosDBTrigger_ROOT_SOLUTION_PATH }}
      
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ${{ env.CosmosDBTrigger_ROOT_SOLUTION_PATH }}
        
      - name: Build Function App for Release
        run: dotnet build --configuration Release --output ./output
        working-directory: ${{ env.AZURE_FUNCTION_CosmosDBTrigger_PATH }}
        
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        #id: fa1
        with:
          app-name: ${{ env.AZURE_CosmosDBTrigger_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTION_CosmosDBTrigger_PATH }}/output'
          publish-profile: ${{ secrets.AZURE_FUNCTION_COSMOSDB_PUBLISH_CREDS }}
