name: Test and Deploy DevOpsStoreConfiguration

on:
  #push:
    #branches: [ main ]
    #paths-ignore: 
      #- '**/README.md'
      #- '**/*.yml'
  #pull_request:
    #branches: [ main ]
  workflow_dispatch:
  
env:
  AZURE_DevOpsStoreConfiguration_FUNCTIONAPP_NAME: DevOpsStoreConfiguration-FA
  AZURE_FUNCTION_DevOpsStoreConfiguration_PATH: DevOpsStoreConfiguration/MCD.FN.ManageGit
  DevOpsStoreConfiguration_ROOT_SOLUTION_PATH: 'DevOpsStoreConfiguration'
  DOTNET_VERSION: 3.1.x
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:    
      - name: Get the latest source code commit
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{ env.DevOpsStoreConfiguration_ROOT_SOLUTION_PATH }}

      - name: Build for Testing
        run: dotnet build --no-restore
        working-directory: ${{ env.DevOpsStoreConfiguration_ROOT_SOLUTION_PATH }}
      
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ${{ env.DevOpsStoreConfiguration_ROOT_SOLUTION_PATH }}
        
      - name: Build Function App for Release
        run: dotnet build --configuration Release --output ./output
        working-directory: ${{ env.AZURE_FUNCTION_DevOpsStoreConfiguration_PATH }}
        
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_DevOpsStoreConfiguration_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTION_DevOpsStoreConfiguration_PATH }}/output'
          publish-profile: ${{ secrets.AZURE_FUNCTION_DEVOPSSTORE_PUBLISH_CREDS }}
